Added FE documentation
oakestra/documentation pull request #8
Opened 2023-09-21 13:12 UTC by giobart

2023-10-02 08:24 UTC, danimair9 approved these changes

2023-11-07 16:13 UTC, nitindermohan requested changes

2023-11-07 16:13 UTC, nitindermohan commented on content/docs/dashboard/features.md
> +Creating a service is the main task of the dashboard, as described in other parts of the documentation,
Can you add reference to https://www.oakestra.io/docs/getstarted/get-started-app/ highlighting that it is possible to deploy application from the API browser as well but the dashboard makes everything a "one stop shop"?

2023-11-07 16:13 UTC, nitindermohan commented on content/docs/dashboard/features.md
> +
The deployment descriptor is different from the example descriptor on the wiki already (https://www.oakestra.io/docs/getstarted/get-started-app/). Can we keep things consistent?

2023-11-07 16:13 UTC, nitindermohan commented on content/docs/dashboard/features.md
>  This is the default role of a user, he can create applications and services and manage them accordingly.
A description of other roles in dashboard is also needed

2023-11-07 16:13 UTC, nitindermohan commented on content/docs/dashboard/features.md
> +and they can use the resources provided within the organization to deploy new services.
Please add a description of "Organization"

2023-11-07 16:13 UTC, nitindermohan commented on content/docs/dashboard/features.md
> +**Important:** This feater is implemented in the frontend but not yet 100% in the backend and therefore might not work yet.
Is there an issue for it? If no, can we create one and add a link to the issue? That ways once we overhaul we can close the issue and remember to update the wiki as well.

2023-11-07 16:22 UTC, nitindermohan requested changes

2023-11-07 16:22 UTC, nitindermohan commented on content/docs/dashboard/features.md
> +**Important:** This feater is implemented in the frontend but not yet 100% in the backend and therefore might not work yet.
Found the open issue: https://github.com/oakestra/oakestra/issues/182

2023-11-15 16:59 UTC, nitindermohan approved these changes
Looks good @danimair9

2023-12-14 14:46 UTC, merged